version: '3.7'

services:
  postgres:
    container_name: rest-api_postgres
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret

volumes:
  postgres: